names:
    coal_block\:0: coal_block
    stone\:0: stone
    nether_brick\:0: nether_brick
    netherrack\:0: netherrack
    redstone_block\:0: redstone_block
    bedrock\:0: bedrock
    clay\:0: clay
    gold_block\:0: gold_block
    stained_clay\:4: hardened_clay_stained_yellow
    stained_clay\:8: hardened_clay_stained_silver
    stained_clay\:11: hardened_clay_stained_blue
    stained_clay\:13: hardened_clay_stained_green
    stained_clay\:14: hardened_clay_stained_red
    stained_clay\:15: hardened_clay_stained_black
    wool\:4: wool_colored_yellow
    wool\:7: wool_colored_gray
    wool\:8: wool_colored_silver
    wool\:13: wool_colored_green
    wool\:14: wool_colored_red
    hay_block\:4: hay_block_top
    hay_block\:8: hay_block_top
    wood_step\:5: planks_spruce
    wood\:5: planks_spruce
    quartz_block\:0_top: quartz_block_top
    quartz_block\:0_side: quartz_block_side
    quartz_block\:0_bottom: quartz_block_bottom
    step\:7_top: quartz_block_top
    step\:7_side: quartz_block_side
    step\:7_bottom: quartz_block_bottom
    step\:15_top: quartz_block_top
    step\:15_side: quartz_block_side
    step\:15_bottom: quartz_block_bottom